### ISSUE TITLE
[Issue]: TheRock gfx90a builds failing for the past week or so

### ISSUE THREAD

**Issue by BenWibking** [ROCm/TheRock#841]
### Problem Description

I've been using [this script](https://gist.github.com/BenWibking/a970c916ce69561dce3d9ae72e27981c) to build TheRock using the provided manylinux build container since April 2025, and in the past week or so, builds have been consistently failing with errors like this:

```
[15/128] Building sub-project therock-boost (in background)
ninja: build stopped: subcommand failed.
Test project /mnt/home/wibkingb/TheRock/build
      Start  1: build_tools_artifacts_test
 1/27 Test  #1: build_tools_artifacts_test ............................   Passed    0.09 sec
      Start  2: build_tools_fetch_artifacts_test
 2/27 Test  #2: build_tools_fetch_artifacts_test ......................   Passed    0.33 sec
      Start  3: build_tools_fileset_tool_test
 3/27 Test  #3: build_tools_fileset_tool_test .........................   Passed    0.28 sec
      Start  4: build_tools_github_actions_configure_ci_test
 4/27 Test  #4: build_tools_github_actions_configure_ci_test ..........   Passed    0.09 sec
      Start  5: therock-validate-shared-lib-librocm-openblas.so
 5/27 Test  #5: therock-validate-shared-lib-librocm-openblas.so .......   Passed    0.06 sec
      Start  6: therock-validate-shared-lib-libamd.so
 6/27 Test  #6: therock-validate-shared-lib-libamd.so .................***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libamd.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libamd.so: cannot open shared object file: No such file or directory

      Start  7: therock-validate-shared-lib-libcamd.so
 7/27 Test  #7: therock-validate-shared-lib-libcamd.so ................***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libcamd.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libcamd.so: cannot open shared object file: No such file or directory

      Start  8: therock-validate-shared-lib-libccolamd.so
 8/27 Test  #8: therock-validate-shared-lib-libccolamd.so .............***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libccolamd.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libccolamd.so: cannot open shared object file: No such file or directory

      Start  9: therock-validate-shared-lib-libcholmod.so
 9/27 Test  #9: therock-validate-shared-lib-libcholmod.so .............***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libcholmod.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libcholmod.so: cannot open shared object file: No such file or directory

      Start 10: therock-validate-shared-lib-libcolamd.so
10/27 Test #10: therock-validate-shared-lib-libcolamd.so ..............***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libcolamd.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libcolamd.so: cannot open shared object file: No such file or directory

      Start 11: therock-validate-shared-lib-libsuitesparseconfig.so
11/27 Test #11: therock-validate-shared-lib-libsuitesparseconfig.so ...***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libsuitesparseconfig.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/third-party/SuiteSparse/dist/lib/host-math/lib/libsuitesparseconfig.so: cannot open shared object file: No such file or directory

      Start 12: therock-validate-shared-lib-libbz2.so
12/27 Test #12: therock-validate-shared-lib-libbz2.so .................   Passed    0.04 sec
      Start 13: therock-validate-shared-lib-libdrm.so
13/27 Test #13: therock-validate-shared-lib-libdrm.so .................   Passed    0.03 sec
      Start 14: therock-validate-shared-lib-libdrm_amdgpu.so
14/27 Test #14: therock-validate-shared-lib-libdrm_amdgpu.so ..........   Passed    0.04 sec
      Start 15: therock-validate-shared-lib-libnuma.so
15/27 Test #15: therock-validate-shared-lib-libnuma.so ................   Passed    0.04 sec
      Start 16: therock-validate-shared-lib-libsqlite3.so
16/27 Test #16: therock-validate-shared-lib-libsqlite3.so .............   Passed    0.04 sec
      Start 17: therock-validate-shared-lib-libz.so
17/27 Test #17: therock-validate-shared-lib-libz.so ...................   Passed    0.03 sec
      Start 18: therock-validate-shared-lib-libzstd.so
18/27 Test #18: therock-validate-shared-lib-libzstd.so ................   Passed    0.03 sec
      Start 19: therock-validate-shared-lib-libelf.so
19/27 Test #19: therock-validate-shared-lib-libelf.so .................   Passed    0.04 sec
      Start 20: therock-validate-shared-lib-libdw.so
20/27 Test #20: therock-validate-shared-lib-libdw.so ..................   Passed    0.04 sec
      Start 21: therock-validate-shared-lib-libasm.so
21/27 Test #21: therock-validate-shared-lib-libasm.so .................   Passed    0.04 sec
      Start 22: therock-validate-shared-lib-libamd_comgr.so
22/27 Test #22: therock-validate-shared-lib-libamd_comgr.so ...........***Failed    0.04 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/compiler/amd-comgr/dist/lib/libamd_comgr.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/compiler/amd-comgr/dist/lib/libamd_comgr.so: cannot open shared object file: No such file or directory

      Start 23: therock-validate-shared-lib-libhsa-runtime64.so
23/27 Test #23: therock-validate-shared-lib-libhsa-runtime64.so .......***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/core/ROCR-Runtime/dist/lib/libhsa-runtime64.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/core/ROCR-Runtime/dist/lib/libhsa-runtime64.so: cannot open shared object file: No such file or directory

      Start 24: therock-validate-shared-lib-libamdhip64.so
24/27 Test #24: therock-validate-shared-lib-libamdhip64.so ............***Failed    0.04 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/core/clr/dist/lib/libamdhip64.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/core/clr/dist/lib/libamdhip64.so: cannot open shared object file: No such file or directory

      Start 25: therock-validate-shared-lib-libhiprtc-builtins.so
25/27 Test #25: therock-validate-shared-lib-libhiprtc-builtins.so .....***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/core/clr/dist/lib/libhiprtc-builtins.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/core/clr/dist/lib/libhiprtc-builtins.so: cannot open shared object file: No such file or directory

      Start 26: therock-validate-shared-lib-libhiprtc.so
26/27 Test #26: therock-validate-shared-lib-libhiprtc.so ..............***Failed    0.03 sec
Validating shared library: /mnt/home/wibkingb/TheRock/build/core/clr/dist/lib/libhiprtc.soTraceback (most recent call last):
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 24, in <module>
    main(sys.argv[1:])
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 20, in main
    run(args)
  File "/mnt/home/wibkingb/TheRock/build_tools/validate_shared_library.py", line 12, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /mnt/home/wibkingb/TheRock/build/core/clr/dist/lib/libhiprtc.so: cannot open shared object file: No such file or directory

      Start 27: therock-examples-cpp-sdk-user
27/27 Test #27: therock-examples-cpp-sdk-user .........................***Failed    0.52 sec
-- Removing build dir /mnt/home/wibkingb/TheRock/build/examples/cpp-sdk-user
Internal cmake changing into directory: /mnt/home/wibkingb/TheRock/build/examples/cpp-sdk-user
======== CMake output     ======
The CXX compiler identification is GNU 14.2.1
The HIP compiler identification is unknown
CMake Error at /opt/_internal/pipx/venvs/cmake/lib/python3.12/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineHIPCompiler.cmake:217 (message):
  The ROCm root directory:

   /mnt/home/wibkingb/TheRock/build/dist/rocm

  does not contain the HIP runtime CMake package, expected at one of:

   /mnt/home/wibkingb/TheRock/build/dist/rocm/lib/cmake/hip-lang/hip-lang-config.cmake
   /mnt/home/wibkingb/TheRock/build/dist/rocm/lib64/cmake/hip-lang/hip-lang-config.cmake

Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


Configuring incomplete, errors occurred!
======== End CMake output ======
Error: cmake execution failed
CMake Error at /mnt/home/wibkingb/TheRock/examples/clean_configure_test_project.cmake:40 (message):
  Failed to execute test process




56% tests passed, 12 tests failed out of 27

Total Test time (real) =   2.21 sec

The following tests FAILED:
	  6 - therock-validate-shared-lib-libamd.so (Failed)
	  7 - therock-validate-shared-lib-libcamd.so (Failed)
	  8 - therock-validate-shared-lib-libccolamd.so (Failed)
	  9 - therock-validate-shared-lib-libcholmod.so (Failed)
	 10 - therock-validate-shared-lib-libcolamd.so (Failed)
	 11 - therock-validate-shared-lib-libsuitesparseconfig.so (Failed)
	 22 - therock-validate-shared-lib-libamd_comgr.so (Failed)
	 23 - therock-validate-shared-lib-libhsa-runtime64.so (Failed)
	 24 - therock-validate-shared-lib-libamdhip64.so (Failed)
	 25 - therock-validate-shared-lib-libhiprtc-builtins.so (Failed)
	 26 - therock-validate-shared-lib-libhiprtc.so (Failed)
	 27 - therock-examples-cpp-sdk-user (Failed)
Errors while running CTest
du: cannot access 'build/dist/rocm': No such file or directory
tar: build/dist/rocm: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

### Operating System

Ubuntu 22.04.5 LTS

### CPU

AMD EPYC 9654 96-Core Processor

### GPU

N/A

### ROCm Version

ROCm 7.0pre

### Steps to Reproduce

Perform the containerized TheRock build using this script: https://gist.github.com/BenWibking/a970c916ce69561dce3d9ae72e27981c

**Comment by marbre** [comment]
Form the log above, it seems CMake 4.0 is used:
> CMake Error at /opt/_internal/pipx/venvs/cmake/lib/python3.12/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineHIPCompiler.cmake:217 (message):

Not all of the components can be successfully compiled with CMake 4.0, which is addressed with commit a91fc1d. Can you test if using CMake < 4.0.0 solves the issue? The "shared objects not found" issue might be a different one though.

**Comment by BenWibking** [comment]
I re-ran the build script with the latest manylinux container today, and added `cmake --version` to the build script. It shows that CMake 3.25 is used.

However, the build still failed. I didn't capture the full build log, but I re-ran it after the initial failed build and captured that log (attached):
[therock_build_log.txt](https://github.com/user-attachments/files/20840332/therock_build_log.txt)

**Comment by stellaraccident** [comment]
I think I see the issue. Last Friday, we tried a "normal" bump to head on the manylinux docker and it broke the world. When we set the project up, we unfortunately weren't using pinned dockers and were just tracking the `main` branch packages.

The problem started here: https://github.com/ROCm/TheRock/commit/bbba4a1f27c615d9ca3c1210a0e396188821b431
We then "rolled back" here by switching everything in the project to be based on pin instead of the branch tag: https://github.com/ROCm/TheRock/commit/8b3da6f51ae47600cc1c6bc24dfa21d2905c2bec

And for the last week, we've been iterating to get the new manylinux head to work cleanly. Most recent is here: https://github.com/ROCm/TheRock/pull/874

Given the chaos last week, I'm taking extra time to review/validate the #874 patch before landing it. In the meantime, please use the manylinux pin that our CI [uses from this patch above](https://github.com/ROCm/TheRock/commit/8b3da6f51ae47600cc1c6bc24dfa21d2905c2bec): `ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:044b113562629f4bd2ec5d2e64b32eee11562d48fb1a75d7493daec9dd8d8292`

We'll put this in a text file or something eventually so you don't just have to scrape it from random files, but just hardcoding it was the way we fixed the break last week and we are still recovering.

Sorry, generally the "main" tag of that docker image is unstable and I didn't notice that you were caught up in our sloppy prior update processes.

**Comment by stellaraccident** [comment]
(with that said, these issues you are seeing are RPATH related and I would not generally expect them to be so sensitive -- I think we may have more root causing to do here, but let us start by eliminating the configuration drift)

**Comment by BenWibking** [comment]
Using the pinned container fixed the build. Thanks.
